# Generated by roxytest: Do not edit by hand!

# File R/merge_gedcoms.R: @tests

test_that("Function merge_records() @ L317", {
  expect_error(merge_records(tidyged::sample555, c("@I1@","@F1@")))
})

