# Generated by roxytest: Do not edit by hand!


test_that("Function remove_dates_for_tests() @ L199", {
  expect_snapshot_value(remove_dates_for_tests(tidyged::sample555), "json2")
})


test_that("Function split_gedcom() @ L220", {
  expect_snapshot_value(split_gedcom(sample555, c("@I1@","@S1@")), "json2")
  expect_snapshot_value(split_gedcom(sample555, c("@I1@","@S1@"), FALSE), "json2")
})

